# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3



pipelines:
  default:
    - step:
        caches:
          - node
        script:
            - pipe: microsoft/azure-web-apps-deploy:1.0.3
              variables:
                AZURE_APP_ID: 0e9a5add-ce1e-4cf5-b3ed-ae875d94b26c
                AZURE_PASSWORD: 09411b12-f78d-43f1-8eae-007f79856024
                AZURE_TENANT_ID: cd96aad7-ce2e-4d09-85e5-8ecd4d2ca8be
                AZURE_RESOURCE_GROUP: '<string>'
                AZURE_APP_NAME: '<string>'
                ZIP_FILE: '<string>'
                # SLOT: '<string>' # Optional.
                # DEBUG: '<boolean>' # Optional.
          
          
          

